version: '3'
services:
  nginx:
    build: ./nginx
    ports:
      - "80:8080"
    networks:
      - contenta
    volumes:
      - ./www:/var/www:cached
    # this ensures that nginx's upstream host "php" will always have
    # valid DNS when we're starting up
    depends_on:
      - php
  php:
    build: ./php
    ports:
      - "9000:9000"
    volumes:
      - ./www:/var/www:cached
    env_file:
      - .env
    networks:
      - contenta
  database:
    build: ./database
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - contenta

volumes:
  data:

networks:
  contenta:
